# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions:
        patterns:
          - '*'
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: build
      include: scope
    groups:
      actions-runtime:
        patterns:
          - '@actions/*'
      node:
        patterns:
          - '*'
        exclude-patterns:
          - '@actions/*'
